### ISSUE TITLE
JLinkException "unspecified error" when connect to MIMXRT1062

### ISSUE THREAD

**Issue by bbilas** [square/pylink#165]
There is an exception when `connect` function is called with `MIMXRT1062xxx6A` device argument (right now I don't have any other MCUs for testing).

pylink 1.0.0
Arch Linux
Python 3.10
SEGGER J-Link Tools 7.84a

Simple test script:

<pre>
import pylink

if __name__ == '__main__':
   serial_no = '000051XXXXXX'
   jlink = pylink.JLink()

   # Open a connection to your J-Link.
   jlink.open(serial_no)

   # Connect to the target device.
   jlink.connect('MIMXRT1062xxx6A', verbose=True)
</pre>

<pre>
Traceback (most recent call last):
  File "/tmp/test.py", line 11, in <module>
    jlink.connect('MIMXRT1062xxx6A', verbose=True)
  File "/usr/lib/python3.10/site-packages/pylink/jlink.py", line 142, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pylink/jlink.py", line 1137, in connect
    raise errors.JLinkException(result)
pylink.errors.JLinkException: Unspecified error.
</pre>

SEGGER J-Link is correctly recognized using e.g `product_name` function.

**Comment by bbilas** [comment]
Shame on me, didn't notice `Troubleshooting` area. The default JTAG interface instead of SWD was a reason.
