### ISSUE TITLE
JLink SDK for v8 has changed?

### ISSUE THREAD

**Issue by lab313ru** [square/pylink#216]
When using JLink with a fresh installed v8.10 pylink crashes:
```
Exception ignored on calling ctypes callback function: <function JLink.__init__.<locals>.<lambda> at 0x00000201E50384A0>
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\pylink\jlink.py", line 324, in <lambda>
  File "c:\Python312\Lib\logging\__init__.py", line 1526, in debug
  File "c:\Python312\Lib\logging\__init__.py", line 1800, in isEnabledFor
TypeError: 'NoneType' object is not callable
Exception ignored on calling ctypes callback function: <function JLink.__init__.<locals>.<lambda> at 0x00000201E50384A0>
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\pylink\jlink.py", line 324, in <lambda>
  File "c:\Python312\Lib\logging\__init__.py", line 1526, in debug
  File "c:\Python312\Lib\logging\__init__.py", line 1800, in isEnabledFor
TypeError: 'NoneType' object is not callable
Exception ignored in: <function Library.__del__ at 0x00000201E515A340>
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\pylink\library.py", line 323, in __del__
  File "c:\Python312\Lib\site-packages\pylink\library.py", line 467, in unload
AttributeError: 'NoneType' object has no attribute 'c_void_p'

Exception ignored on calling ctypes callback function: <function JLink.__init__.<locals>.<lambda> at 0x0000025C1FB64360>
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\pylink\jlink.py", line 323, in <lambda>
  File "c:\Python312\Lib\logging\__init__.py", line 1538, in info
  File "c:\Python312\Lib\logging\__init__.py", line 1800, in isEnabledFor
TypeError: 'NoneType' object is not callable
Exception ignored on calling ctypes callback function: <function JLink.__init__.<locals>.<lambda> at 0x0000025C1FB64360>
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\pylink\jlink.py", line 323, in <lambda>
  File "c:\Python312\Lib\logging\__init__.py", line 1538, in info
  File "c:\Python312\Lib\logging\__init__.py", line 1800, in isEnabledFor
TypeError: 'NoneType' object is not callable
Exception ignored in: <function Library.__del__ at 0x0000025C1FA1E340>
Traceback (most recent call last):
  File "c:\Python312\Lib\site-packages\pylink\library.py", line 323, in __del__
  File "c:\Python312\Lib\site-packages\pylink\library.py", line 467, in unload
AttributeError: 'NoneType' object has no attribute 'c_void_p
```

**Comment by hkpeprah** [comment]
Thanks for the bug report. Might require some thinking to figure out how to handle this in a backwards compatible way 🤔
